In [1]:
import pandas as pd

In [2]:
pd.read_excel('C:\Users\kumak\iNeuron classes\Resources\Live Class\pandas\Attribute DataSet.xlsx')

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (3630516818.py, line 1)

In [3]:
# resolved above error with 'r' infront of file path.
# refer below
https://stackoverflow.com/questions/37400974/error-unicode-error-unicodeescape-codec-cant-decode-bytes-in-position-2-3

SyntaxError: invalid syntax (3842090664.py, line 3)

In [4]:
pd.read_excel(r'C:\Users\kumak\iNeuron classes\Resources\Live Class\pandas\Attribute DataSet.xlsx')

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [ ]:
#  instead of providing path or location, we can upload the file in current working directory and use, 
#  refer below.

In [5]:
pd.read_csv('haberman (1).csv')

     30  64   1  1.1
0    30  62   3    1
1    30  65   0    1
2    31  59   2    1
3    31  65   4    1
4    33  58  10    1
..   ..  ..  ..  ...
300  75  62   1    1
301  76  67   0    1
302  77  65   3    1
303  78  65   1    2
304  83  58   2    2

[305 rows x 4 columns]

In [6]:


df = pd.read_excel(r'C:\Users\kumak\iNeuron classes\Resources\Live Class\pandas\Attribute DataSet.xlsx')

In [7]:
#  dataframe : (same as sql table)
#  a tabular structure, 

type(df)

pandas.core.frame.DataFrame

In [8]:
df

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [16]:
# how to handle 'nul' value.
# from different sheets, i need to review data in excel?

In [9]:
df1= pd.read_excel(r'C:\Users\kumak\iNeuron classes\Resources\Live Class\pandas\Attribute DataSet.xlsx', sheet_name= 'sample_sheet', header = 0, names = ['A', 'B','C']
)

In [32]:
df1

                     A    B  C
1  khai kj jj    csjco    1  0
2  wdwdq       kcsh cs    0  1
3  khai kj jj    csjco    1  1
4  cXQDq         csjco    0  0
5  khai kj jj     qceq    1  1
6  d cqd         csjco    0  0
7  khai kj jj    csjco    1  1
8  ac dw          cqeq    0  0
9  cqd           csjco    1  0
10 khai kj jj    csjco    0  1
11 khai kj jj      cqd    1  0
12 c qdq         csjco    1  0
13 khai kj jj    cqedq    0  0
14 khai kj jj    csjco    1  1
15 khai kj jj    csjco  cqe  0
16 khai kj jj    csjco    1  0
17 khai kj jj    csjco    0  1
18 khai kj jj     cqeq    1  0
19 khai kj jj    csjco    0  1
20 khai kj jj      cqe    1  0
21 khai kj jj    csjco    1  0
22 khai kj jj        q    0  1
23 khai kj jj    csjco    1  0
24 khai kj jj    csjco    1  1
25 khai kj jj    csjco    1  0
26 khai kj jj      cqe    0  1
27 khai kj jj    csjco    1  0
28 khai kj jj    csjco    1  1
29 khai kj jj    csjco    0  0

In [33]:
#  pandas takes first row record as column header by default

In [10]:
df.head(2)

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0

In [11]:
df.head()

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0

In [36]:
df.head(20)

    s.no        test     many one   must
0      1  khai kj jj    csjco    1     0
1      2       wdwdq  kcsh cs    0     1
2      3  khai kj jj    csjco    1     1
3      4       cXQDq    csjco    0     0
4      5  khai kj jj     qceq    1     1
5      6       d cqd    csjco    0     0
6      7  khai kj jj    csjco    1     1
7      8       ac dw     cqeq    0     0
8      9         cqd    csjco    1     0
9     10  khai kj jj    csjco    0     1
10    11  khai kj jj      cqd    1     0
11    12       c qdq    csjco    1     0
12    13  khai kj jj    cqedq    0     0
13    14  khai kj jj    csjco    1     1
14    15  khai kj jj    csjco  cqe     0
15    16  khai kj jj    csjco    1     0
16    17  khai kj jj    csjco    0     1
17    18  khai kj jj     cqeq    1     0
18    19  khai kj jj    csjco    0     1
19    20  khai kj jj      cqe    1     0

In [12]:
df.tail()

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [13]:
df.tail(10)

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
490,641665398,Casual,Low,4.8,free,winter,bowneck,full,natural,polyster,chiffon,bow,solid,0
491,964917582,Casual,Average,5.0,L,Summer,o-neck,sleevless,natural,cotton,NaN,NaN,NaN,1
492,859922576,cute,Average,4.6,M,Spring,o-neck,halfsleeve,natural,acrylic,chiffon,NaN,NaN,0
493,817353671,bohemian,Low,4.6,free,Summer,o-neck,sleevless,natural,cotton,chiffon,none,solid,1
494,990559192,Brief,Average,4.7,M,winter,o-neck,halfsleeve,natural,acrylic,chiffon,NaN,striped,0
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [14]:
dataframe2 = pd.read_csv(r"C:\Users\kumak\iNeuron classes\Resources\Live Class\pandas\haberman.csv", header = 0, names = ['Age', "Patient's year of operaion", 'No of Positive nodes', 'SUrvival status'])

In [15]:
dataframe2

     Age  Patient's year of operaion  No of Positive nodes  SUrvival status
0     30                          62                     3                1
1     30                          65                     0                1
2     31                          59                     2                1
3     31                          65                     4                1
4     33                          58                    10                1
..   ...                         ...                   ...              ...
300   75                          62                     1                1
301   76                          67                     0                1
302   77                          65                     3                1
303   78                          65                     1                2
304   83                          58                     2                2

[305 rows x 4 columns]

In [16]:
dataframe3 = pd.read_csv(r"C:\Users\kumak\iNeuron classes\Resources\Live Class\pandas\test_delimitor_dataset.csv", delimiter = '@')

In [17]:
dataframe3

     30  64   1  1.1
0    30  62   3    1
1    30  65   0    1
2    31  59   2    1
3    31  65   4    1
4    33  58  10    1
..   ..  ..  ..  ...
300  75  62   1    1
301  76  67   0    1
302  77  65   3    1
303  78  65   1    2
304  83  58   2    2

[305 rows x 4 columns]

In [18]:
dataframe_from_git = pd.read_csv("https://raw.githubusercontent.com/selva86/datasets/master/Smarket.csv")

In [19]:
dataframe_from_git

      Year   Lag1   Lag2   Lag3   Lag4   Lag5   Volume  Today Direction
0     2001  0.381 -0.192 -2.624 -1.055  5.010  1.19130  0.959        Up
1     2001  0.959  0.381 -0.192 -2.624 -1.055  1.29650  1.032        Up
2     2001  1.032  0.959  0.381 -0.192 -2.624  1.41120 -0.623      Down
3     2001 -0.623  1.032  0.959  0.381 -0.192  1.27600  0.614        Up
4     2001  0.614 -0.623  1.032  0.959  0.381  1.20570  0.213        Up
...    ...    ...    ...    ...    ...    ...      ...    ...       ...
1245  2005  0.422  0.252 -0.024 -0.584 -0.285  1.88850  0.043        Up
1246  2005  0.043  0.422  0.252 -0.024 -0.584  1.28581 -0.955      Down
1247  2005 -0.955  0.043  0.422  0.252 -0.024  1.54047  0.130        Up
1248  2005  0.130 -0.955  0.043  0.422  0.252  1.42236 -0.298      Down
1249  2005 -0.298  0.130 -0.955  0.043  0.422  1.38254 -0.489      Down

[1250 rows x 9 columns]

In [20]:
df_from_web = pd.read_html("https://www.basketball-reference.com/leagues/NBA_2015_totals.html")

In [21]:
df_from_web

[      Rk          Player Pos Age   Tm   G  GS    MP   FG  FGA  ...   FT%  ORB  \
 0      1      Quincy Acy  PF  24  NYK  68  22  1287  152  331  ...  .784   79
 1      2    Jordan Adams  SG  20  MEM  30   0   248   35   86  ...  .609    9
 2      3    Steven Adams   C  21  OKC  70  67  1771  217  399  ...  .502  199
 3      4     Jeff Adrien  PF  28  MIN  17   0   215   19   44  ...  .579   23
 4      5   Arron Afflalo  SG  29  TOT  78  72  2502  375  884  ...  .843   27
 ..   ...             ...  ..  ..  ...  ..  ..   ...  ...  ...  ...   ...  ...
 670  490  Thaddeus Young  PF  26  TOT  76  68  2434  451  968  ...  .655  127
 671  490  Thaddeus Young  PF  26  MIN  48  48  1605  289  641  ...  .682   75
 672  490  Thaddeus Young  PF  26  BRK  28  20   829  162  327  ...  .606   52
 673  491     Cody Zeller   C  22  CHO  62  45  1487  172  373  ...  .774   97
 674  492    Tyler Zeller   C  25  BOS  82  59  1731  340  619  ...  .823  146

      DRB  TRB  AST  STL BLK  TOV   PF   PTS
 0    222  301   68   27  22   60  147   398
 1     19   28   16   16   7   14   24    94
 2    324  523   66   38  86   99  222   537
 3     54   77   15    4   9    9   30    60
 4    220  247  129   41   7  116  167  1035
 ..   ...  ...  ...  ...  ..  ...  ...   ...
 670  284  411  173  124  25  117  171  1071
 671  170  245  135   86  17   75  115   685
 672  114  166   38   38   8   42   56   386
 673  265  362  100   34  49   62  156   472
 674  319  465  113   18  52   76  205   833

 [675 rows x 30 columns]]

In [22]:
type(df_from_web)

list

In [23]:
df_from_web[0]

,Rk,Player,Pos,Age,Tm,G,GS,MP,FG,FGA,...,FT%,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1,Quincy Acy,PF,24,NYK,68,22,1287,152,331,...,.784,79,222,301,68,27,22,60,147,398
1,2,Jordan Adams,SG,20,MEM,30,0,248,35,86,...,.609,9,19,28,16,16,7,14,24,94
2,3,Steven Adams,C,21,OKC,70,67,1771,217,399,...,.502,199,324,523,66,38,86,99,222,537
3,4,Jeff Adrien,PF,28,MIN,17,0,215,19,44,...,.579,23,54,77,15,4,9,9,30,60
4,5,Arron Afflalo,SG,29,TOT,78,72,2502,375,884,...,.843,27,220,247,129,41,7,116,167,1035
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
670,490,Thaddeus Young,PF,26,TOT,76,68,2434,451,968,...,.655,127,284,411,173,124,25,117,171,1071
671,490,Thaddeus Young,PF,26,MIN,48,48,1605,289,641,...,.682,75,170,245,135,86,17,75,115,685
672,490,Thaddeus Young,PF,26,BRK,28,20,829,162,327,...,.606,52,114,166,38,38,8,42,56,386
673,491,Cody Zeller,C,22,CHO,62,45,1487,172,373,...,.774,97,265,362,100,34,49,62,156,472
674,492,Tyler Zeller,C,25,BOS,82,59,1731,340,619,...,.823,146,319,465,113,18,52,76,205,833

In [24]:
len(df_from_web)

1

In [25]:
df_json_link = pd.read_json("https://api.github.com/repos/pandas-dev/pandas/issues")

In [26]:
df_json_link

,url,repository_url,labels_url,comments_url,events_url,html_url,id,node_id,number,title,...,closed_at,author_association,active_lock_reason,body,reactions,timeline_url,performed_via_github_app,state_reason,draft,pull_request
0,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/54233,1817009075,I_kwDOAA0YD85sTVuz,54233,"BUG: ""table name"" form of `pd.read_sql()` doe...",...,NaT,NONE,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
1,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/54232,1816932794,PR_kwDOAA0YD85WJ9C5,54232,DOC: Imporve `json_normalize` record_prefix an...,...,NaT,CONTRIBUTOR,NaN,- [ ] closes #54121 (Replace xxxx with the Gi...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
2,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/54231,1816932319,I_kwDOAA0YD85sTC_f,54231,"BUG: Docs does not build on macos, due to EOFE...",...,NaT,NONE,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
3,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/54230,1816870831,PR_kwDOAA0YD85WJxPi,54230,Fixed groupby error with nullable types,...,NaT,NONE,NaN,- [x] closes #54206 \r\n- [x] [Tests added and...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
4,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/54229,1816868972,I_kwDOAA0YD85sSzhs,54229,DEPR: Positional arguments in to_* I/O methods,...,NaT,MEMBER,NaN,These should all be keyword only except for bu...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
5,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/54227,1816689386,I_kwDOAA0YD85sSHrq,54227,ENH: a readable sample function or an improvement,...,NaT,NONE,NaN,### Feature Type\n\n- [X] Adding new functiona...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
6,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/54226,1816552876,PR_kwDOAA0YD85WIz4E,54226,DEPR: idxmin/idxmax with all-NA,...,NaT,MEMBER,NaN,- [x] closes #51276 (Replace xxxx with the Git...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
7,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/54225,1816520062,PR_kwDOAA0YD85WItdj,54225,CLN/ASV: remove downcast param (deprecated) fr...,...,NaT,CONTRIBUTOR,NaN,None,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
8,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/54224,1816512127,PR_kwDOAA0YD85WIr0n,54224,PERF: DataFrame.transpose for pyarrow-backed,...,NaT,CONTRIBUTOR,NaN,- [x] [Tests added and passed](https://pandas....,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
9,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/54223,1816498433,PR_kwDOAA0YD85WIot5,54223,PERF: ArrowDtype.__eq__,...,NaT,CONTRIBUTOR,NaN,Micro-perf improvement:\r\n\r\n```\r\nimport p...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
10,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/54222,1816496485,PR_kwDOAA0YD85WIoRD,54222,CI/TST: Address some warnings,...,NaT,MEMBER,NaN,None,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
11,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/54220,1816445866,PR_kwDOAA0YD85WIdeM,54220,DOC: Simplify contributing intro,...,NaT,MEMBER,NaN,* Reduced some preamble\r\n* Updated some link...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
12,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/54219,1816415144,PR_kwDOAA0YD85WIW2J,54219,DEPR: Series.argsort NA behavior,...,NaT,MEMBER,NaN,- [ ] closes #xxxx (Replace xxxx with the GitH...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
13,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/54218,1816253128,PR_kwDOAA0YD85WHz-S,54218,CI: Try out pre-commit.ci again,...,NaT,MEMBER,NaN,Will need to enable the pre-commit Github app,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
14,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/54217,1816206681,PR_kwDOAA0YD85WHpkR,54217,DOC: Fixing EX01 - Added examples,...,NaT,MEMBER,NaN,- [x] All [code checks passed](https://pandas....,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
15,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/54216,1815855321,PR_kwDOAA0YD85WGdoi,54216,DOC: Removed InvalidComparisonÂ andÂ LossySetIte...,...,NaT,MEMBER,NaN,- [x] All [code checks passed](https://pandas....,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
16,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/54214,1814840772,PR_kwDOAA0YD85WDD04,54214,FIX: query() and isin() fail on period type co...,...,NaT,CONTRIBUTOR,NaN,- [X] closes #54199\r\n- [ ] [Tests added and ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,1.0,{'url': 'https://api.github.com/repos/pandas-d...
17,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/54212,1814501132,I_kwDOAA0YD85sJxcM,54212,BUG: Doc build fails locally due to `rstjinja`...,...,NaT,NONE,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
18,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/54209,1814325893,PR_kwDOAA0YD85WBSTu,54209,TST: Use numpy random generator for testing data,...,NaT,MEMBER,NaN,"This PR diff is large, but essentially it enab...",{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
19,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/54206,1813812535,I_kwDOAA0YD85sHJU3,54206,BUG: Grouped rank incorrect behaviour with nul...,...,NaT,CONTRIBUTOR,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
20,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/54204,1813437622,I_kwDOAA0YD85sFty2,54204,BUG: Scatter plot has a hardcoded default value,...,NaT,NONE,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
21,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/54203,1813359655,I_kwDOAA0YD85sFawn,54203,BUG: `AttributeError` when `rolling.agg` use `...,...,NaT,NONE,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
22,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/54200,1812855663,PR_kwDOAA0YD85V8O2-,54200,CI: Bump pandas-gbq to one that doesn't pin py...,...,NaT,MEMBER,NaN,- [ ] closes #xxxx (Replace xxxx with the GitH...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
23,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/54199,1812736733,I_kwDOAA0YD85sDCrd,54199,BUG: `.query()` and `isin()` fail on period ty...,...,NaT,NONE,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
24,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/pull/54198,1812706435,PR_kwDOAA0YD85V7uJj,54198,POC: pass date_unit to values_for_json,...,NaT,MEMBER,NaN,@WillAyd this isn't working (or even compiling...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,0.0,{'url': 'https://api.github.com/repos/pandas-d...
25,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/54195,1812112194,I_kwDOAA0YD85sAqNC,54195,BUG:,...,NaT,NONE,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
26,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/54194,1812052615,I_kwDOAA0YD85sAbqH,54194,BUG: in a level of `MultiIndex` tz info is los...,...,NaT,NONE,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
27,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/54193,1812036176,I_kwDOAA0YD85sAXpQ,54193,"BUG: pd.Series.describe ignores include, exclu...",...,NaT,NONE,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
28,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/54192,1811897004,I_kwDOAA0YD85r_1qs,54192,BUG: pd.to_latex does not escape percentage si...,...,NaT,NONE,NaN,### Pandas version checks\n\n- [X] I have chec...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN
29,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://api.github.com/repos/pandas-dev/pandas...,https://github.com/pandas-dev/pandas/issues/54191,1811847359,I_kwDOAA0YD85r_pi_,54191,"BUG: `convert_dtypes(dtype_backend=""pyarrow"")`...",...,NaT,NONE,NaN,### Pandas version checks\r\n\r\n- [X] I have ...,{'url': 'https://api.github.com/repos/pandas-d...,https://api.github.com/repos/pandas-dev/pandas...,NaN,NaN,NaN,NaN

In [27]:
df_json_link.columns

Index(['url', 'repository_url', 'labels_url', 'comments_url', 'events_url',
       'html_url', 'id', 'node_id', 'number', 'title', 'user', 'labels',
       'state', 'locked', 'assignee', 'assignees', 'milestone', 'comments',
       'created_at', 'updated_at', 'closed_at', 'author_association',
       'active_lock_reason', 'body', 'reactions', 'timeline_url',
       'performed_via_github_app', 'state_reason', 'draft', 'pull_request'],
      dtype='object')

In [28]:
df_json_link['user']

0     {'login': 'kalekundert', 'id': 298132, 'node_i...
1     {'login': 'luke396', 'id': 77875500, 'node_id'...
2     {'login': 'Tialo', 'id': 65392801, 'node_id': ...
3     {'login': 'KladeRe', 'id': 81648517, 'node_id'...
4     {'login': 'lithomas1', 'id': 47963215, 'node_i...
5     {'login': 'nagaprakashv', 'id': 13671867, 'nod...
6     {'login': 'jbrockmendel', 'id': 8078968, 'node...
7     {'login': 'lukemanley', 'id': 8519523, 'node_i...
8     {'login': 'lukemanley', 'id': 8519523, 'node_i...
9     {'login': 'lukemanley', 'id': 8519523, 'node_i...
10    {'login': 'mroeschke', 'id': 10647082, 'node_i...
11    {'login': 'mroeschke', 'id': 10647082, 'node_i...
12    {'login': 'jbrockmendel', 'id': 8078968, 'node...
13    {'login': 'mroeschke', 'id': 10647082, 'node_i...
14    {'login': 'DeaMariaLeon', 'id': 11835246, 'nod...
15    {'login': 'DeaMariaLeon', 'id': 11835246, 'nod...
16    {'login': 'dannyi96', 'id': 15380498, 'node_id...
17    {'login': 'DavidToneian', 'id': 25615622, 'nod...
18    {'login': 'mroeschke', 'id': 10647082, 'node_i...
19    {'login': 'NMAC427', 'id': 9914734, 'node_id':...
20    {'login': 'pgorczak', 'id': 1765698, 'node_id'...
21    {'login': 'XytHu', 'id': 9063883, 'node_id': '...
22    {'login': 'lithomas1', 'id': 47963215, 'node_i...
23    {'login': 'davidgilbertson', 'id': 4443482, 'n...
24    {'login': 'jbrockmendel', 'id': 8078968, 'node...
25    {'login': 'strpeter', 'id': 2798595, 'node_id'...
26    {'login': 'maread99', 'id': 56914820, 'node_id...
27    {'login': 'natalymr', 'id': 31903015, 'node_id...
28    {'login': 'phelps-sg', 'id': 4571777, 'node_id...
29    {'login': 'randolf-scholz', 'id': 39696536, 'n...
Name: user, dtype: object

In [29]:
df_json_link['user'][0]

{'login': 'kalekundert',
 'id': 298132,
 'node_id': 'MDQ6VXNlcjI5ODEzMg==',
 'avatar_url': 'https://avatars.githubusercontent.com/u/298132?v=4',
 'gravatar_id': '',
 'url': 'https://api.github.com/users/kalekundert',
 'html_url': 'https://github.com/kalekundert',
 'followers_url': 'https://api.github.com/users/kalekundert/followers',
 'following_url': 'https://api.github.com/users/kalekundert/following{/other_user}',
 'gists_url': 'https://api.github.com/users/kalekundert/gists{/gist_id}',
 'starred_url': 'https://api.github.com/users/kalekundert/starred{/owner}{/repo}',
 'subscriptions_url': 'https://api.github.com/users/kalekundert/subscriptions',
 'organizations_url': 'https://api.github.com/users/kalekundert/orgs',
 'repos_url': 'https://api.github.com/users/kalekundert/repos',
 'events_url': 'https://api.github.com/users/kalekundert/events{/privacy}',
 'received_events_url': 'https://api.github.com/users/kalekundert/received_events',
 'type': 'User',
 'site_admin': False}

In [30]:
df_json_link['title']

0     BUG: "table name" form of  `pd.read_sql()` doe...
1     DOC: Imporve `json_normalize` record_prefix an...
2     BUG: Docs does not build on macos, due to EOFE...
3               Fixed groupby error with nullable types
4        DEPR: Positional arguments in to_* I/O methods
5     ENH: a readable sample function or an improvement
6                       DEPR: idxmin/idxmax with all-NA
7     CLN/ASV: remove downcast param (deprecated) fr...
8          PERF: DataFrame.transpose for pyarrow-backed
9                               PERF: ArrowDtype.__eq__
10                        CI/TST: Address some warnings
11                     DOC: Simplify contributing intro
12                     DEPR: Series.argsort NA behavior
13                      CI: Try out pre-commit.ci again
14                    DOC: Fixing EX01 - Added examples
15    DOC: Removed InvalidComparisonÂ andÂ LossySetIte...
16    FIX: query() and isin() fail on period type co...
17    BUG: Doc build fails locally due to `rstjinja`...
18    TST: Use numpy random generator for testing data
19    BUG: Grouped rank incorrect behaviour with nul...
20      BUG: Scatter plot has a hardcoded default value
21    BUG: `AttributeError` when `rolling.agg` use `...
22    CI: Bump pandas-gbq to one that doesn't pin py...
23    BUG: `.query()` and `isin()` fail on period ty...
24               POC: pass date_unit to values_for_json
25                                                BUG:
26    BUG: in a level of `MultiIndex` tz info is los...
27    BUG: pd.Series.describe ignores include, exclu...
28    BUG: pd.to_latex does not escape percentage si...
29    BUG: `convert_dtypes(dtype_backend="pyarrow")`...
Name: title, dtype: object

In [31]:
df_attributes = pd.read_excel(r"C:\Users\kumak\iNeuron classes\Resources\Live Class\pandas\Attribute DataSet.xlsx")

In [32]:
df_attributes

,Dress_ID,Style,Price,Rating,Size,Season,NeckLine,SleeveLength,waiseline,Material,FabricType,Decoration,Pattern Type,Recommendation
0,1006032852,Sexy,Low,4.6,M,Summer,o-neck,sleevless,empire,NaN,chiffon,ruffles,animal,1
1,1212192089,Casual,Low,0.0,L,Summer,o-neck,Petal,natural,microfiber,NaN,ruffles,animal,0
2,1190380701,vintage,High,0.0,L,Automn,o-neck,full,natural,polyster,NaN,NaN,print,0
3,966005983,Brief,Average,4.6,L,Spring,o-neck,full,natural,silk,chiffon,embroidary,print,1
4,876339541,cute,Low,4.5,M,Summer,o-neck,butterfly,natural,chiffonfabric,chiffon,bow,dot,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,713391965,Casual,Low,4.7,M,Spring,o-neck,full,natural,polyster,NaN,NaN,solid,1
496,722565148,Sexy,Low,4.3,free,Summer,o-neck,full,empire,cotton,NaN,NaN,NaN,0
497,532874347,Casual,Average,4.7,M,Summer,v-neck,full,empire,cotton,NaN,lace,solid,1
498,655464934,Casual,Average,4.6,L,winter,boat-neck,sleevless,empire,silk,broadcloth,applique,print,1
499,919930954,Casual,Low,4.4,free,Summer,v-neck,short,empire,cotton,Corduroy,lace,solid,0

In [33]:
#  convert into json

df_attributes.to_json('test.json')

In [34]:
pwd

'C:\\Users\\kumak\\iNeuron classes\\Pandas'

In [35]:
#  creating file 
df_attributes.to_csv(r"C:\Users\kumak\Desktop\test.csv")

In [38]:
#  sep = and delimitor while creating the file 
df_attributes.to_csv(r"C:\Users\kumak\Desktop\test1234.csv", sep = '#')

In [40]:
df_attributes.to_csv(r"C:\Users\kumak\Desktop\test12345.csv", index = False)

TASK 

we have this attributes data sets, and dress sales data base.
connected based on dress id.  


Mysql : 
    
    1. Create a  table attribute dataset and dress dataset
    2. Do a bulk load for these two table for respective dataset 
    3. read these dataset in pandas as a dataframe 
    4. Convert attribute dataset in json format 
    5. Store this dataset into mongodb
    6. in sql task try to perform left join operation with attrubute dataset and dress dataset on column Dress_ID
    7. Write a sql query to find out how many unique dress that we have based on dress id 
    8. Try to find out how mnay dress is having recommendation 0
    9. Try to find out total dress sell for individual dress id 
    10. Try to find out a third highest most selling dress id